defaultEntryPoints = ["http", "https"]

[entryPoints]
  [entryPoints.http]
    address = ":80"
      [entryPoints.http.redirect]
      entryPoint = "https"
  [entryPoints.https]
  address = ":443"
    [entryPoints.https.tls]

[docker]
endpoint = "unix:///var/run/docker.sock"
watch = true
exposedbydefault = false

[acme]
email = "erwinsteffens@gmail.nl"
storage = "/etc/traefik/acme/acme.json"
entryPoint = "https"
onDemand = true

[[acme.domains]]
  main = "erwinsteffens.com"
[[acme.domains]]
  main = "erwinsteffens.nl"  